config/routes.rb
Rails.application.routes.draw do
 
  get 'news', to: 'pages#news'
  get "chartkick/index"
  get "pages/team"
  get "pages/contact"
  get 'legal', to: 'pages#legal'
  
  get 'dashboard', to: 'dashboard#index', as: :user_dashboard
  
  resources :dashboard, only: [:index]
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :contact_form, only: [:new, :create], path: "contact_form"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # CRUD for production
  resources :productions

  # CRUD for raw materials
  resources :raw_materials

  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'

end

app/controllers/contact_form_controller.rb
class ContactFormController < ApplicationController
  def create
    # Extract form parameters from the 'contact_form' input
    @first_name = params[:contact_form][:first_name]
    @last_name = params[:contact_form][:last_name]
    @email = params[:contact_form][:email]
    @message = params[:contact_form][:message]

    # Send the extracted data to the NotifierMailer to send an email
    NotifierMailer.simple_message(@first_name, @last_name, @contact_email, @message).deliver_now
    
    flash[:success] = "Votre message a bien été envoyé."
    redirect_to :root
  end
end

app/helpers/contact_form_helper.rb
module ContactFormHelper
end

app/views/contact_form/_contact_form.html.erb
<div class="mb-3 custom-margin">
  <div class="container">
    <div class="row">
      <h1 style="padding-top: 50px">Contactez-nous !</h1>
      <div class="col-md-6 mb-4 mt-5">
        <div class="mb-3">
          <%= form_with scope: :contact_form, url: contact_form_index_path, method: :post, local: true, class: "container" do |form| %>
            <div class="form-group">
              <%= form.label :Prénom %>
              <%= form.text_field :Prénom, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :Nom %>
              <%= form.text_field :Nom, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :email %>
              <%= form.email_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :message %>
              <%= form.text_area :message, class: "form-control" %>
            </div>
            <br>
            <%= form.submit "Envoyer", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
   
    </div>
  </div>
</div>

app/views/contact_form/new.html.erb
<div class="mb-3 custom-margin">
  <div class="container">
    <div class="row">
      <h1 style="padding-top: 50px">Contactez-nous !</h1>
      <div class="col-md-6 mb-4 mt-5">
        <div class="mb-3">
          <%= form_with scope: :contact_form, url: contact_form_index_path, method: :post, local: true, class: "container" do |form| %>
            <div class="form-group">
              <%= form.label :first_name %>
              <%= form.text_field :first_name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :last_name %>
              <%= form.text_field :last_name, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :email %>
              <%= form.email_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= form.label :message %>
              <%= form.text_area :message, class: "form-control" %>
            </div>
            <br>
            <%= form.submit "Submit", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
      <div class="col-md-4 d-flex justify-content-center align-items-center">
        <%= image_tag("contact.png", alt: "Background image", class: "img-fluid mb-4") %>
      </div>
    </div>
  </div>
</div>