config/routes.rb
Rails.application.routes.draw do
 
  get 'news', to: 'pages#news'
  get "chartkick/index"
  get "pages/team"
  get "pages/contact"
  get 'legal', to: 'pages#legal'
  
  get 'dashboard', to: 'dashboard#index', as: :user_dashboard
  
  resources :dashboard, only: [:index]
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :contact_form, only: [:new, :create], path: "contact_form"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # CRUD for production
  resources :productions

  # CRUD for raw materials
  resources :raw_materials

  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root 'home#index'

end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-container">
    <div class="footer-column">
      <h3>A propos</h3>
      <ul>
        <li><%= link_to 'Notre équipe', "#{pages_team_path}#team" %></li>
        <li><%= link_to 'Contact', "#{pages_team_path}#contact" %></li>
      </ul>
    </div>

    <div class="footer-column">
      <h3>Partenaire</h3>
      <ul>
        <%= link_to 'https://www.thehackingproject.org/', target: "_blank" do %>
        <%= image_tag "logothp.png", alt: "Logo", class: "footer-logo" %>
        <% end %>
      </ul>
    </div>

    <div class="footer-column">
      <h3>Mentions Légales</h3>
      <ul>
        <li><%= link_to 'CGU', "#{legal_path}#cgu" %></li>
        <li><%= link_to 'Politique de Confidentialité', "#{legal_path}#privacy-policy" %></li>
      </ul>
    </div>
  </div>
  <div class="footer-copyright">
    <p>© 2024 ECO². Tous droits réservés.</p>
    <p>
      Conçu par
      <%= link_to 'Zaineb Padilla', 'https://www.linkedin.com/in/zaineb-padilla-7415a25a/', target: '_blank' %>,
      <%= link_to 'Stéphane Dubail', 'https://www.linkedin.com/in/st%C3%A9phane-dubail-53005032b/', target: '_blank' %> et
      <%= link_to 'Nora Vergoz', 'https://www.linkedin.com/in/nora-vergoz-26534432b/', target: '_blank' %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">

<head>
  <title><%= content_for(:title) || "Zero Waste Project" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="manifest" href="/manifest.json">
  <link rel="apple-touch-icon" href="/icon.png">


 
  <%= javascript_importmap_tags %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= favicon_link_tag 'logoeco2.png' %>
</head>

<body>
  <% flash.each do |key, message| %>
  <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %>">
    <%= message %>
  </div>
  <% end %>
  <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
    <div class="container w-100 d-flex justify-content-between align-items-center">
      <div class="d-flex align-items-center ms-auto me-auto">

        <%= image_tag "Vector_blanc.png", alt: "Logo", class: "navbar-logo me-1" %>
        <%= link_to 'ECO²', root_path, class: 'navbar-brand' %>
      </div>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarContent">
      <div class="mx-auto">
        <ul class="nav justify-content-center">
          <li class="nav-item">
            <%= link_to 'Accueil', root_path, class: 'nav-link active', 'aria-current': 'page' %>
          </li>
          <li class="nav-item">
          <%= link_to 'Actualité', news_path, class: 'nav-link' %>
        </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Mon Tableau de bord #{current_user.first_name}", dashboard_index_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Mes Productions', productions_path, class: 'btn btn-link nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Mon Profil", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= button_to 'Déconnexion', destroy_user_session_path, method: :delete, class: 'btn btn-link nav-link' %>
          </li>
          <% else %>
          <li class="nav-item">
            <%= link_to 'Connexion', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Inscription', new_user_registration_path, class: 'nav-link' %>
          </li>
          <% end %>
        </ul>
  </nav>
  <%= yield %>
  <%= render 'layouts/footer' %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
  <%= javascript_include_tag "alerts.js" %>
</body>

</html>